### PR TITLE
Add Select All to DuplicatesContactFixFragment

### PR DESCRIPTION
**Pull request by Quadriyanney**

### CODE REVIEW

**Comment by rasheedsulayman** [comment]
Hello @Quadriyanney, The PR title says work-in-progress, do you want me to hold on on the review?

**Comment by rasheedsulayman** [comment]
Also, please exclude local (.idea, etc) & generated folders from git.

**Comment by Quadriyanney** [comment]
The PR is ready for review now. Removed local files that were pushed with the first commit.

**Comment by rasheedsulayman** [comment]
Welldone @Quadriyanney ...

**Pull request merged**
